apiVersion: v1
kind: Pod
metadata:
  name: nginx 
  namespace: roboshop
  labels:
     name: nginx 
     project: roboshop 
spec:
  containers:
    - name: nginx
      image: krishnachaitanyadevops1/debug:v1
      ports: 
      - Containerport: 80 




 