apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
  DB_USER: "shipping"
---
apiVersion: v1
kind: Secret
metadata:
  name: shipping-secret
  namespace: roboshop
type: Opaque
stringData:
  DB_PASS: "RoboShop@1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: krishnachaitanyadevops1/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: shipping-secret
              key: DB_PASS
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: shipping
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
